### ISSUE TITLE
你好，想问下，

### ISSUE THREAD

**Issue by wy19901227** [zy445566/myBlog#1]
平时你用node开发的时候，遇到后台逻辑有需要计算的时候是怎么解决的呢？ 写一个多线程的模块吗？
还有其他说明方式吗？

**Comment by zy445566** [comment]
其实我觉得写一个多线程模块在设计上是下策，因为如果稍微设计不当就会极大增加代码的复杂度。
如果有条件建议还是使用容器伸缩的策略。
如果没有这个条件，建议就封装成简易调用的模型，比较好的例子就是napajs。即使用某个多线程库也建议封装一层，这样以后为官方多线程铺路也方便。
